spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

graphql:
  spqr:
    http:
      endpoint: /graphql

    gui:
      enabled: true
      endpoint: /schema