spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?allowPublicKeyRetrieval=true
    username: root
    password: rhrnak45

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  redis:
    host: localhost
    port: 6379

graphql:
  spqr:
    http:
      endpoint: /graphql

    gui:
      enabled: true
      endpoint: /schema