version: "3.7"
services:
  db:
    platform: linux/x86_64 # for m1 silicon
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/.env

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
        - backend

networks:
  backend:
